[build]
  command = "npm run build"
  publish = "dist/blog/browser"

# Desabilitar framework detection e plugin Angular  
[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_ANGULAR_RUNTIME = "false"

# Regras de redirect
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
